CREATE PROCEDURE APCHKDetail(IN:FYR CHAR(4))
RETURNS(
		IDAPACCT CHAR(45),
		DATEINVC DECIMAL(9),
		VENDOR CHAR(60),
		INVNUM CHAR(22),
		PONUM CHAR(22),
		ACTUAL DECIMAL(19, 3),
		ENCUM DECIMAL(19, 3),
		FISCYR CHAR(4)
		);
BEGIN
	SELECT
		IDAPACCT,
		DATEINVC,
		GLDESC AS VENDOR,
		IDINVC AS INVNUM,
		CONVERT(NULL(), SQL_CHAR),
		AMTEXTNDHC,
		0 AS ENCUM,
		FISCYR 
	FROM
		APATR
	WHERE
		((FISCYR=:FYR)
		AND
		(TYPEBTCH='PY'));
END;