CREATE PROCEDURE APINVDetail(IN:FYR CHAR(4))
RETURNS(
		FISCYR CHAR(4),
		IDAPACCT CHAR(45),
		DATEINVC DECIMAL(9),
		VENDOR CHAR(60),
		INVNUM CHAR(22),
		PONUM CHAR(22),
		ACTUAL DECIMAL(19, 3),
		ENCUM DECIMAL(19, 3)
		);
BEGIN
	SELECT
		APATR.FISCYR,
		APATR.IDAPACCT,
		APATR.DATEINVC,
		APVEN.VENDNAME AS VENDOR,
		APATR.IDINVC AS INVNUM,
		APOBL.IDPONBR AS PONUM,
		APATR.AMTEXTNDHC AS ACTUAL,
		0 AS ENCUM
	FROM 
		(APATR LEFT OUTER JOIN APOBL 
			ON ((APATR.IDINVC = APOBL.IDINVC) 
			AND (APATR.IDVEND = APOBL.IDVEND))) 
		LEFT OUTER JOIN APVEN 
			ON (APATR.IDVEND = APVEN.VENDORID)
	WHERE
		(((APATR.FISCYR)=:FYR) 
		AND ((APATR.TYPEBTCH)<>'PY') 
		AND ((APATR.SRCETYPE)<>'CR'));
END;