CREATE PROCEDURE FISCALBUDGETS(IN:FYR CHAR(4))
RETURNS(
		ACCTDESC CHAR(60),
		FISCYR CHAR(4),
		ACCTFRMT CHAR(45),
		ACCTID CHAR(45),
		FSCSDSG CHAR (1),
		OPENBAL DECIMAL(19, 3),
		NETPERD1 DECIMAL(19, 3),
		NETPERD2 DECIMAL(19, 3),
		NETPERD3 DECIMAL(19, 3),
		NETPERD4 DECIMAL(19, 3),
		NETPERD5 DECIMAL(19, 3),
		NETPERD6 DECIMAL(19, 3),
		NETPERD7 DECIMAL(19, 3),
		NETPERD8 DECIMAL(19, 3),
		NETPERD9 DECIMAL(19, 3),
		NETPERD10 DECIMAL(19, 3),
		NETPERD11 DECIMAL(19, 3),
		NETPERD12 DECIMAL(19, 3),
		YTDBALActual DECIMAL(19, 3),
		ACCTSEG CHAR(15),
		DEPRT CHAR(15),
		PROJT CHAR(15)
		);
BEGIN
	SELECT
		GLAMF.ACCTDESC,
		GLAFS.FSCSYR AS FISCYR,
		GLAMF.ACCTFMTTD AS ACCTFRMT,
		GLAFS.ACCTID,
		GLAFS.FSCSDSG,
		GLAFS.OPENBAL,
		GLAFS.NETPERD1, 
		GLAFS.NETPERD2, 
		GLAFS.NETPERD3, 
		GLAFS.NETPERD4, 
		GLAFS.NETPERD5, 
		GLAFS.NETPERD6, 
		GLAFS.NETPERD7, 
		GLAFS.NETPERD8, 
		GLAFS.NETPERD9, 
		GLAFS.NETPERD10, 
		GLAFS.NETPERD11, 
		GLAFS.NETPERD12,
		(openbal + netperd1 + netperd2 +
		netperd3 + netperd4 + netperd5 +
		netperd6 + netperd7 + netperd8 +
		netperd9 + netperd10 + netperd11 +
		netperd12) AS YTDBALActual,
		GLAMF.ACSEGVAL01, 
		GLAMF.ACSEGVAL02, 
		GLAMF.ACSEGVAL03 
	FROM 
		GLAMF INNER JOIN GLAFS ON GLAMF.ACCTID = GLAFS.ACCTID
	
	WHERE 
		((GLAFS.FSCSYR = :FYR) AND (GLAFS.FSCSDSG = 'A'));
END;
