CREATE PROCEDURE GLJEDetail(IN:FYR CHAR(4))
RETURNS(
		FISCALYR CHAR(4),
		ACCTID CHAR(45),
		JRNLDATE DECIMAL(9),
		VENDOR CHAR(60),
		INVNUM CHAR(22),
		PONUM CHAR(22),
		ACTUAL DECIMAL(19, 3),
		ENCUM DECIMAL(19, 3)
		);
BEGIN
	SELECT
		FISCALYR,
		ACCTID,
		JRNLDATE,
		JNLDTLDESC AS Vendor,
		JNLDTLREF AS INVNUM,
		CONVERT(NULL(), SQL_CHAR),
		TRANSAMT,
		0 AS ENCUM 
	FROM
		GLPOST
	WHERE
		((FISCALYR=:FYR)
		AND
		((SRCETYPE='JE') OR (SRCETYPE='CR')));
END;