CREATE PROCEDURE POCRDDetail(IN:FYR CHAR(4))
RETURNS(
		FISCYR CHAR(4),
		ACCTSEG CHAR(5),
		DEPRT CHAR(3),
		PROJT CHAR(7),
		ACCTFRMT CHAR(45),
		DT DECIMAL(9),
		VENDOR CHAR(60),
		INVNUM CHAR(22),
		PONUM CHAR(22),
		ACTUAL DECIMAL(19, 3),
		ENCUM DECIMAL(19, 3)
		);
BEGIN
	SELECT
		POCRNH1.FISCYEAR AS FISCYR,
		GLAMF.ACSEGVAL01 AS ACCTSEG,
		GLAMF.ACSEGVAL02 AS DEPRT,
		GLAMF.ACSEGVAL03 AS PROJT,
		GLAMF.ACCTFMTTD AS ACCTFRMT,
		POCRNH1.DATE,
		POCRNH1.VDNAME AS VENDOR,
		POCRNH1.CRNNUMBER AS INVNUM,
		POCRNH1.PONUMBER AS PONUM,
		0-POCRNL.EXTENDED AS Actual,
		0 AS ENCUM 
	FROM 
		((GLAMF LEFT JOIN POCRNL ON GLAMF.ACCTFMTTD = POCRNL.GLACEXPENS) 
		LEFT JOIN POCRNH1 ON POCRNL.CRNHSEQ = POCRNH1.CRNHSEQ) 
		LEFT JOIN POCRNAH ON POCRNH1.CRNHSEQ = POCRNAH.CRNHSEQ
	GROUP BY 
		GLAMF.ACSEGVAL01, 
		GLAMF.ACSEGVAL02, 
		GLAMF.ACSEGVAL03,
		GLAMF.ACCTFMTTD, 
		POCRNH1.DATE, 
		POCRNH1.VDNAME, 
		POCRNH1.CRNNUMBER, 
		POCRNH1.PONUMBER, 
		POCRNL.EXTENDED, 
		POCRNH1.FISCYEAR,  
		POCRNAH.CRNHSEQ
	HAVING 
		((POCRNH1.FISCYEAR=:FYR) 
		AND 
		(POCRNAH.CRNHSEQ Is Null)
		AND 
		(POCRNL.EXTENDED<>0));
END;