CREATE PROCEDURE POINVDetail(IN:FYR CHAR(4))
RETURNS(
		ACCTSEG CHAR(5),
		DEPRT CHAR(3),
		PROJT CHAR(7),
		ACCTFRMT CHAR(45),
		DT DECIMAL(9),
		VENDOR CHAR(60),
		INVNUM CHAR(22),
		PONUM CHAR(22),
		ACTUAL DECIMAL(19, 3),
		ENCUM DECIMAL(19, 3)
		);
BEGIN
	SELECT
		GLAMF.ACSEGVAL01 AS ACCTSEG,
		GLAMF.ACSEGVAL02 AS DEPRT,
		GLAMF.ACSEGVAL03 AS PROJT,
		GLAMF.ACCTFMTTD AS ACCTFRMT,
		POINVH1.DATE,
		POINVH1.VDNAME AS VENDOR,
		POINVH1.INVNUMBER AS INVNUM,
		POINVH1.PONUMBER AS PONUM,
		POINVL.EXTENDED AS Actual,
		0 AS ENCUM 
	FROM 
		((GLAMF LEFT OUTER JOIN POINVL ON GLAMF.ACCTFMTTD = POINVL.GLACEXPENS) 
		LEFT OUTER JOIN POINVH1 ON POINVL.INVHSEQ = POINVH1.INVHSEQ) 
		LEFT OUTER JOIN POINVAH ON POINVH1.INVHSEQ = POINVAH.INVHSEQ 
	GROUP BY 
		GLAMF.ACSEGVAL01, 
		GLAMF.ACSEGVAL02,
		GLAMF.ACSEGVAL03,
		GLAMF.ACCTFMTTD, 
		POINVH1.DATE, 
		POINVH1.VDNAME, 
		POINVH1.INVNUMBER, 
		POINVH1.PONUMBER, 
		POINVL.EXTENDED, 
		POINVH1.FISCYEAR, 
		POINVAH.INVHSEQ
	HAVING 
		((POINVL.EXTENDED > 0) 
		AND 
		(POINVH1.FISCYEAR = :FYR) 
		AND 
		(POINVAH.INVHSEQ IS NULL));
END;
