CREATE PROCEDURE PORCTDetail(IN:FYR CHAR(4))
RETURNS(
		ACCTSEG CHAR(5),
		DEPRT CHAR(3),
		PROJT CHAR(7),
		ACCTFRMT CHAR(45),
		DT DECIMAL(9),
		VENDOR CHAR(60),
		INVNUM CHAR(22),
		PONUM CHAR(22),
		ACTUAL DECIMAL(19, 3),
		ENCUM DECIMAL(19, 3),
		FISCYR CHAR(4)
		);
BEGIN
	SELECT
		GLAMF.ACSEGVAL01 AS ACCTSEG,
		GLAMF.ACSEGVAL02 AS DEPRT,
		GLAMF.ACSEGVAL03 AS PROJT,
		GLAMF.ACCTFMTTD AS ACCTFRMT,
		PORCPH1.DATE,
		PORCPH1.VDNAME AS VENDOR,
		PORCPH1.RCPNUMBER AS INVNUM,
		PORCPH1.PONUMBER AS PONUM,
		PORCPL.EXTENDED AS Actual,
		0 AS ENCUM,
		PORCPH1.FISCYEAR AS FISCYR  
	FROM 
		GLAMF LEFT OUTER JOIN 
		(PORCPH1 RIGHT OUTER JOIN PORCPL ON PORCPH1.RCPHSEQ = PORCPL.RCPHSEQ) 
		ON GLAMF.ACCTFMTTD = PORCPL.GLACEXPENS
	GROUP BY 
		GLAMF.ACSEGVAL01, 
		GLAMF.ACSEGVAL02,
		GLAMF.ACSEGVAL03, 
		PORCPL.EXTENDED, 
		GLAMF.ACCTFMTTD, 
		PORCPH1.DATE, 
		PORCPH1.VDNAME, 
		PORCPH1.RCPNUMBER, 
		PORCPH1.PONUMBER, 
		PORCPH1.FISCYEAR, 
		PORCPH1.ISCOMPLETE 
	HAVING 
		((PORCPL.EXTENDED > 0) 
		AND 
		(PORCPH1.FISCYEAR = :FYR) 
		AND 
		(PORCPH1.ISCOMPLETE = 0));
END;
